/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.amp.tms.enumerated;

import static com.amp.tms.constants.Constants.IVR_PATH;
import com.amp.tms.service.FreeswitchConfiguration;

/**
 *
 * 
 */
public enum RecordedPhrases {

    CONFIRM_PAYMENT_AMOUNT,
    CREDIT_CARD_EXPIRATION,
    CREDIT_CARD_NUMBER,
    CREDIT_CARD_NUMBER_INVALID,
    CREDIT_CARD_ZIP,
    CREDIT_CARD_CCV,
    CURRENT_PAYMENT_OF_PART_1,
    CURRENT_PAYMENT_OF_PART_2,
    DNC,
    ENTER_YOU_SSN,
    ENTER_ZIP_CODE_ON_FILE,
    I_AM_SORRY_I_CANT_FIND_ACCOUNT,
    I_FOUND_A_LOAN,
    INVALID_ENTRY,
    IS_THAT_CORRECT,
    MAIN_PROMPT,
    MENU_RECENTLY_CHANGED,
    PAYMENT_SELECTION_DUE,
    PAYMENT_SELECTION_MONTHLY,
    PAYMENT_SELECTION_2,
    ENTER_PAYMENT_AMOUNT,
    YOU_SELECT_PAYMENT_OF,
    PLEASE_WAIT_CALL_TRANSFER,
    PLEASE_WAIT_FOR_NEXT_AGENT,
    VOICEMAIL_PROMPT_AFTER_HOUR_PART1_CASHCALL,
    VOICEMAIL_PROMPT_AFTER_HOUR_PART2,
    VOICEMAIL_TO_LEAVE_VOICEMAIL_PRESS_1,
    VOICEMAIL_TO_LEAVE_VOICEMAIL_STATIC_CASHCALL,
    SORRY_COULD_NOT_PROCESS_YOUR_REQUEST_AT_THIS_TIME,
    IF_YOU_LIKE_TO_LEAVE_VOICE_MAIL,
    SORRY_WE_MISSED_YOU_PLEASE_CALL_BACK_DURING_REGULAR_OFFICE_HOUR,
    AFTER_HOUR_IVR_PAYMENT_OPTION_CASHCALL,
    CLOSED_PROMPT_CASHCALL,
    VOICEMAIL_PROMPT,
    PRESS_ONE_OTHERWISE_ANY,
    SELECT_PAYMENT_AMOUNT_PART1,
    SELECT_PAYMENT_AMOUNT_PART2,
    TYPE_OF_PAYMENT,
    WELCOME_TO_CASHCALL_AUTO,
    WELCOME_TO,
    YOU_ENTERED,
    YOUR_BALANCE_AS_OF_TODAY,
    YOUR_NEXT_DUE_DATE,
    YOUR_LAST_PAYMET,
    MADE_ON,
    PAY_OFF_AS_OF,
    PLEASE_CALL_US_BACK_AT,
    AMOUNT_APPLIED_TO_ACCOUNT_1,
    AMOUNT_APPLIED_TO_ACCOUNT_2,
    CREDIT_CARD_FAIL,
    ACH_FAIL,
    ACH_AMOUNT_OF_1,
    ACH_AMOUNT_OF_2,
    HOLD_ANNOUNCE,
    HOLD_ANNOUNCE_PRESS1,
    I_SEE_THE_PHONE_NUMBER_YOUR_CALLING_FROM_IN_OUR_SYSTEM,
    FOR_SECURITY_PURPOSES_PLEASE_ENTER_THE_LAST_4_DIGITS_OF_YOUR_SOCIAL_SECURITY_NUMBER,
    OK_ARE_CALLING_FOR_LOAN_ID_ENDING_IN,
    PRESS_1_IF_CORRECT,
    YOU_LOAN_IS_CURRENTLY_DUE_FOR,
    IN_THE_AMOUNT_OF,
    I_SEE_THAT_YOUR_PAYMENT_IS_SCHEDULED_TO_BE_PAID_ON_THE,
    IF_YOU_ARE_CALLING_TO_CHANGE_THE_PAYMENT_DATE_PLEASE_PRESS_1_NOW_IF_YOU_WOULD_LIKE_TO_SPEAK_TO_A_CUSTOMER_SERVICE_REPRESENTATIVE_PLEASE_PRESS_0_NOW,
    PLEASE_ENTER_THE_DATE_YOU_WOULD_LIKE_THIS_PAYMENT_TO_BE_DRAFTED_PLEASE_ENTER_THE_2_DIGITS_MONTH_2_DIGITS_DAY_AND_2_DIGITS_YEAR__FOR_EXAMPLE_FOR_JANUARY_13_2016_YOU_WOULD_ENTER_011316,
    YOU_HAVE_ENTERED,
    PRESS_1_IF_THIS_DATE_IS_CORRECT_PRESS_2_TO_REENTER_THE_DATE_PRESS_0_TO_SPEAK_TO_A_REPRESENTATIVE,
    TO_USE_THE_CHECKING_ACCOUNT_ON_FILE_ENDING_IN,
    PLEASE_PRESS_1_NOW_PRESS_0_TO_SPEAK_TO_A_REPRESENTATIVE,
    OK_YOUR,
    FIRST_PAYMENT_IN_THE_AMOUNT_OF,
    WILL_BE_PRESENTED_TO_BANK_ACCOUNT_ENDING_IN,
    PRESS_1_TO_CONFIRM_OR_PRESS_0_TO_SPEAK_TO_REPRESENTATIVE,
    PLEASE_PRESS_1_TO_CONFIRM_PLEASE_PRESS_2_TO_TRY_AGAIN_OR_PLEASE_PRESS_0_TO_SPEAK_TO_REPRESENTATIVE,
    THANK_YOU_FOR_YOUR_PAYMENT_IF_YOU_NEED_ADDITIONAL_ASSISTANCE_PLEASE_STAY_ON_THE_LINE,
    THANK_YOU_FOR_YOUR_PAYMENT_IF_YOU_NEED_ADDITIONAL_ASSISTANCE_PLEASE_PRESS_0_NOW,
    SORRY_I_WAS_UNABLE_TO_VERIFY_THAT_ENTRY,
    SORRY_I_AM_UNABLE_TO_FIND_YOUR_ACCOUNT_PLEASE_WAIT_FOR_THE_NEXT_CUSTOMER_SERVICE_REPRESENTATIVE,
    IF_YOU_KNOW_YOUR_LOAN_ID_PLEASE_PRESS_1_TO_ENTER_BY_SOCIAL_SECURITY_NUMBER_PLEASE_PRESS_2_TO_SPEAK_TO_A_CUSTOMER_SERVICE_REPRESENTATIVE_PLEASE_PRESS_0_AT_ANY_TIME,
    PLEASE_ENTER_YOUR_LOAN_NUMBER,
    PLEASE_ENTER_THE_LAST_FOUR_DIGITS_OF_THE_SOCIAL_SECURITY_NUMBER_FOR_THIS_LOA,
    FOR_SECURITY_PURPOSES_PLEASE_ENTER_YOUR_DATE_OF_BIRTH_PLEASE_ENTER_THE_2_DIGITS_MONTH_2_DIGITS_DAY_AND_2_DIGITS_YEAR_FOR_EXAMPLE_FOR_JANUARY_13_1980_YOU_WOULD_ENTER_011380,
    GOODEBYE,
    AGENT_NOT_AVAILABLE,
    CUSTOMER_VERBAL_AGREEMENT,
    THE_TOTAL_PAYMENT_OF,
    WILL_BE_CHARGED_ON,
    THIS_CHARGE_INCLUDES_THE,
    PAYMENT_AND_A,
    CONVENIENCE_FEE,
    IF_PAYMENT_IS_UNSUCCESSFULL_REATTEMPT_12PM,
    WOULD_YOU_LIKE_TO_PROCEED,
    AUTHORIZING_CASHCALL_ACH_AMOUNT,
    FROM_ACCOUNT,
    WITH_ROUTING,
    ON_OR_AFTER,
    IF_CREATE_CHECK_NAME_ON_SIGNATURE,
    THE_PAYMENT_DATE_YOU_HAVE_SELECTED_IS_MORE_THAN_15_DAYS_PAST_THE_DUE_DATE_THIS_PAYMENT_WILL_BE_SUBJECT_TO_A, 
    LATE_FEE_IF_YOU_WISH_TO_KEEP_THIS_DATE_AS_THE_PAYMENT_DATE_AND_INCLUDE_THE, 
    LATE_CHARGE_WITH_THIS_PAYMENT_PRESS_1_IF_YOU_WISH_TO_WISH_TO_CHANGE_THIS_DATE_PRESS_2_OR_0_TO_SPEAK_WITH_A_REPRESENTATIVE;

    public String getAudioPath() {
        String jvmParam = System.getProperty("company.id");

        String name = name();

        if (jvmParam != null) {
            jvmParam = jvmParam.toUpperCase();
            if (jvmParam.equals("LOANME")) {
                name = name.replace("CASHCALL", jvmParam);
            }
        }
        return (IVR_PATH + FreeswitchConfiguration.getIVRVoice() + "/" + FreeswitchConfiguration.getIVRRate() + "/phrase/" + name + ".wav");
    }

}
